module.exports.topicToKeyword = {
    "Topic 1":[
       [
          "cap",
          "crsp",
          "growth",
          "msci",
          "equity",
          "sector",
          "russell",
          "deviation",
          "consumer",
          "the"
       ],
       [
          "https://institutional.vanguard.com/iippdf/pdfs/FS956R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS954R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS938R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS958R.pdf",
          "https://advisors.vanguard.com/iippdf/pdfs/FS3138R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS951R.pdf",
          "https://advisors.vanguard.com/iippdf/pdfs/FS932R.pdf",
          "https://advisors.vanguard.com/iippdf/pdfs/FS967R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS960R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS955R.pdf"
       ]
    ],
    "Topic 2":[
       [
          "ftse",
          "companies",
          "markets",
          "cap",
          "emerging",
          "ﬂftse",
          "london",
          "international",
          "stocks",
          "developed"
       ],
       [
          "https://institutional.vanguard.com/iippdf/pdfs/FS4394R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS936R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS964R.pdf",
          "https://advisors.vanguard.com/iippdf/pdfs/FS3369R.pdf",
          "https://advisors.vanguard.com/iippdf/pdfs/FS4393R.pdf",
          "https://advisors.vanguard.com/iippdf/pdfs/FS4430R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS991R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS3184R.pdf",
          "https://advisors.vanguard.com/iippdf/pdfs/FS962R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS963R.pdf"
       ]
    ],
    "Topic 3":[
       [
          "bond",
          "ratings",
          "from",
          "treasury",
          "rating",
          "indices",
          "corporate",
          "credit",
          "shall",
          "owners"
       ],
       [
          "https://institutional.vanguard.com/iippdf/pdfs/FS928R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS930R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS924R.pdf",
          "https://advisors.vanguard.com/iippdf/pdfs/FS925R.pdf",
          "https://advisors.vanguard.com/iippdf/pdfs/FS927R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS3145R.pdf",
          "https://advisors.vanguard.com/iippdf/pdfs/FS985R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS3146R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS3147R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS3365R.pdf"
       ]
    ],
    "Topic 4":[
       [
          "sp",
          "growth",
          "jones",
          "dow",
          "midcap",
          "trademarks",
          "equity",
          "deviation",
          "smallcap",
          "spdji"
       ],
       [
          "https://institutional.vanguard.com/iippdf/pdfs/FS3343R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS3347R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS3341R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS3340R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS3342R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS3344R.pdf",
          "https://advisors.vanguard.com/iippdf/pdfs/FS968R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS3346R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS965R.pdf",
          "https://institutional.vanguard.com/iippdf/pdfs/FS920R.pdf"
       ]
    ]
 }